/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurlarRouteImport } from './routes/turlar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimdaRouteImport } from './routes/hakkimda'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as IndexRouteImport } from './routes/index'

const TurlarRoute = TurlarRouteImport.update({
  id: '/turlar',
  path: '/turlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimdaRoute = HakkimdaRouteImport.update({
  id: '/hakkimda',
  path: '/hakkimda',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimda': typeof HakkimdaRoute
  '/iletisim': typeof IletisimRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/turlar': typeof TurlarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimda': typeof HakkimdaRoute
  '/iletisim': typeof IletisimRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/turlar': typeof TurlarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimda': typeof HakkimdaRoute
  '/iletisim': typeof IletisimRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/turlar': typeof TurlarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/hakkimda'
    | '/iletisim'
    | '/sitemap.xml'
    | '/turlar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galeri' | '/hakkimda' | '/iletisim' | '/sitemap.xml' | '/turlar'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/hakkimda'
    | '/iletisim'
    | '/sitemap.xml'
    | '/turlar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  HakkimdaRoute: typeof HakkimdaRoute
  IletisimRoute: typeof IletisimRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TurlarRoute: typeof TurlarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turlar': {
      id: '/turlar'
      path: '/turlar'
      fullPath: '/turlar'
      preLoaderRoute: typeof TurlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimda': {
      id: '/hakkimda'
      path: '/hakkimda'
      fullPath: '/hakkimda'
      preLoaderRoute: typeof HakkimdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  HakkimdaRoute: HakkimdaRoute,
  IletisimRoute: IletisimRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TurlarRoute: TurlarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
